development:
  adapter: postgresql
  database: tweets_dev
  host: localhost
  pool: 5
  timeout: 5000


test:
  adapter: postgresql
  database: tweets_test
  host: localhost
  pool: 5
  timeout: 5000

